### ISSUE TITLE
Missing Modules 2.3 and 4.1

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-133794m3r#9]
👋 Hello @133794m3r , your Campus Advisor training is missing assignment modules 2.3 and 4.1. Please complete those and we'll be happy to process your request for certification.

**Comment by 133794m3r** [comment]
I guess I forgot to include screenshots of it.
[x] 4.1 #10 
[x] 2.3 #11 
[x] 2.3 Branch/Pull request. #7 
@arelia
